### ISSUE TITLE
点击查看队友时出错？

### ISSUE THREAD

**Issue by sanxiadaba** [BruceQiu1996/NPhoenix#6]
在版本号2.4.1中
选英雄阶段右侧的查询队友战绩
点击名字查看战绩，但是当查看一名队友（假设队友A）战绩关闭页面后，再次点击该队友名字（A），页面无反应
点击其他队友（B），页面有反应，且正常显示B队友战绩
然后再点击队友（A）战绩，才能正常显示A的战绩

**Comment by BruceQiu1996** [comment]
是的，目前他是触发的选中项变化的事件，不是点击事件。
